{{- if .Values.pdb.enabled -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "oathkeeper.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "oathkeeper.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  {{ toYaml .Values.pdb.spec }}
{{- end -}}
